--- 
- name: Execute shell script on remote host
  hosts: oem_tst

  tasks:
  - name: Change the working directory to somedir/ before executing the command
    ansible.builtin.shell: /tmp/somescript.sh >> somelog.txt
    args:
      chdir: /tmp/

    